SET PATH=%PATH%;C:\Program Files\PostgreSQL\14\bin
SET DATABASE_URL=postgres://postgres:kostas@127.0.0.1:5432/postgres
SET MUTE_SECURITY=1
SET AUTHENTICATION_KEY_SECRET=q3ChVXVyaNMCPL2q5Gfspj1HODWgYjeZ09BbX1mSW5Q=
SET ENCRYPTION_KEY_SECRET=Mau5yfYtDzCn5coupiFVly_Ml_rHxJBWDK2qiudpdfc=
SET HASH_KEY_SECRET=iq-fJQU_tV5dProQHWE-ePYPcQlNPSb_E2ltfwcAZnI=
SET PASSWORD=iQxWXyHPcO5pDlEU4yeN4iBIQCy4uy1XMoinJB+szR8lCJ1Qd50BTtTKlYLNfuy32Ws6qZtPMw5aWp30jS06KQ==